name: nlp_chatbot
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - c-ares=1.19.0
  - ca-certificates=2022.4.26
  - cachetools=4.2.2
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=39.0.1
  - filelock=3.9.0
  - flask=2.0.3
  - flask-cors=3.0.10
  - flatbuffers=2.0.0
  - freetype=2.10.4
  - frozenlist=1.3.3
  - fsspec=2023.5.0
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - grpcio=1.42.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - huggingface_hub=0.14.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2023.1.0
  - itsdangerous=2.0.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - krb5=1.19.4
  - lcms2=2.15
  - lerc=3.0
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libnghttp2=1.46.0
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - multidict=6.0.2
  - ncurses=6.4
  - networkx=2.8.4
  - nltk=3.8.1
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=23.0
  - pandas=1.5.3
  - pillow=9.4.0
  - pip=23.0.1
  - pooch=1.4.0
  - protobuf=3.20.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyjwt=2.4.0
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - pysolr=3.9.0
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python_abi=3.9
  - pytorch=2.0.1
  - pytz=2022.7
  - pyyaml=6.0
  - re2=2022.04.01
  - readline=8.2
  - regex=2023.5.5
  - requests=2.29.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - sentence-transformers=2.2.2
  - sentencepiece=0.1.95
  - setuptools=66.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tensorboard=2.11.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - termcolor=2.1.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tokenizers=0.13.3
  - torchdata=0.6.1
  - torchtext=0.15.2
  - torchvision=0.13.1
  - tqdm=4.65.0
  - transformers=4.24.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - werkzeug=2.2.3
  - wheel=0.35.1
  - wrapt=1.14.1
  - xz=5.4.2
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
